// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdG-LjlFSRIPMAz7Z68dS9FJDdwnraMiI',
    appId: '1:489176136812:web:36bb2b541e0b8b7c33ec49',
    messagingSenderId: '489176136812',
    projectId: 'userdetails-12f75',
    authDomain: 'userdetails-12f75.firebaseapp.com',
    storageBucket: 'userdetails-12f75.appspot.com',
    measurementId: 'G-M9J5KQPG3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS4S6KI9tuGueZyt4hGaCKAfmls_qXB98',
    appId: '1:489176136812:android:7e4e8d0b21062b7133ec49',
    messagingSenderId: '489176136812',
    projectId: 'userdetails-12f75',
    storageBucket: 'userdetails-12f75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKzKUZkurgJ70JB4_-LZ_iw6FBIAMrmW4',
    appId: '1:489176136812:ios:7707f9912a5ab30a33ec49',
    messagingSenderId: '489176136812',
    projectId: 'userdetails-12f75',
    storageBucket: 'userdetails-12f75.appspot.com',
    iosBundleId: 'com.example.flutterUserDetails',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKzKUZkurgJ70JB4_-LZ_iw6FBIAMrmW4',
    appId: '1:489176136812:ios:ce05935871d3147833ec49',
    messagingSenderId: '489176136812',
    projectId: 'userdetails-12f75',
    storageBucket: 'userdetails-12f75.appspot.com',
    iosBundleId: 'com.example.flutterUserDetails.RunnerTests',
  );
}
